on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main

      - name: Store variables
        run: |
          touch .env
          REDIRECT_OBJ=${{ vars.REDIRECT_OBJ }} >> .env

      - name: Install Dependencies
        run: npm install

      - name: Build for production
        run: npm run build
